import { Routes } from '@angular/router';
import { PageNotFoundComponent } from './shared/components/page-not-found/page-not-found.component';
import { RegisterComponent } from './auth/register/register.component';
import { LoginComponent } from './auth/login/login.component';
import { BookStoreComponent } from './books/book-store/book-store.component';
import { UserOrdersComponent } from './users/user-orders/user-orders.component';
import { ProfileComponent } from './users/profile/profile.component';
import { MaintenanceComponent } from './books/maintenance/maintenance.component';
import { ReturnBookComponent } from './books/return-book/return-book.component';
import { ApprovalRequestsComponent } from './users/approval-requests/approval-requests.component';
import { AllOrdersComponent } from './users/all-orders/all-orders.component';
import { ViewUsersComponent } from './users/view-users/view-users.component';
import { MembershipComponent } from './users/membership/membership.component';
import { AssignLibrarianComponent } from './users/assign-librarian/assign-librarian.component';
import { ReportsComponent } from './books/reports/reports.component';
import { NotificationComponent } from './users/notification/notification.component';
import { InventoryComponent } from './books/inventory/inventory.component';

export const routes: Routes = [
  { path: 'login', component: LoginComponent },
  { path: 'register', component: RegisterComponent },
  { path: 'home', component: BookStoreComponent },
  { path: 'my-orders', component: UserOrdersComponent },
  { path: 'maintenance', component: MaintenanceComponent },
  { path: 'return-book', component: ReturnBookComponent },
  { path: 'approval-requests', component: ApprovalRequestsComponent },
  { path: 'assgin-librarian', component: AssignLibrarianComponent },
  { path: 'all-orders', component: AllOrdersComponent },
  { path: 'view-users', component: ViewUsersComponent },
  { path: 'reports', component: ReportsComponent },
  { path: 'notifications', component: NotificationComponent },
  { path: 'profile', component: ProfileComponent },
  { path: 'inventory', component: InventoryComponent },
  { path: 'membership', component: MembershipComponent },
  { path: '**', component: PageNotFoundComponent },
];
